services:
  web:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres-dev:5432/starter
    networks:
      - my-network
    command: sh -c "npx prisma db pull && npx prisma generate && npm run build && npm start"

networks:
  my-network:
    external: true